/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pegawai;

import config.databaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hafizh Kurniawan
 */
public class rental extends javax.swing.JFrame {
    public String gstatus;
    /**
     * Creates new form rental
     */
    public rental() {
        initComponents();
        tampilkanRental();
    }
    
    public void tampilkanRental() {
        try{
        Connection conn = databaseConnection.connect();
        String sql = "SELECT r.id_rental, r.id_user, r.id_mobil, u.nama, m.merk, m.model, r.tanggal_sewa,"
                + "r.tanggal_kembali, r.total_biaya, r.status FROM rental r INNER JOIN users u "
                + "ON u.id_user = r.id_user INNER JOIN mobil m ON m.id_mobil = r.id_mobil";
        PreparedStatement stmt = conn.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Rental");
        model.addColumn("ID User");
        model.addColumn("Nama");
        model.addColumn("ID Mobil");
        model.addColumn("Merk");
        model.addColumn("Model");
        model.addColumn("Tanggal Sewa");
        model.addColumn("Tanggal Kembali");
        model.addColumn("Total Biaya");
        model.addColumn("Status");
        
        while (rs.next()){
            model.addRow(new Object[]{
            rs.getInt("id_rental"),
            rs.getInt("id_user"),
            rs.getString("nama"),
            rs.getString("id_mobil"),
            rs.getString("merk"),
            rs.getString("model"),
            rs.getString("tanggal_sewa"),
            rs.getString("tanggal_kembali"),
            rs.getString("total_biaya"),
            rs.getString("status")
            });
        }
        
        jTextField1.setEnabled(false);

        
        jTable1.setModel(model);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Error: "+ e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("FORM TRANSAKSI RENTAL");

        jLabel2.setText("ID Rental");

        jLabel3.setText("ID User");

        jLabel4.setText("ID Mobil");

        jLabel5.setText("Tanggal Sewa");

        jLabel6.setText("Tanggal Kembali");

        jLabel8.setText("Status");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pending", "diproses", "selesai", "dibatalkan" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton4.setText("<-");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(251, 251, 251)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 864, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField4)
                                    .addComponent(jTextField3)
                                    .addComponent(jTextField2)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int idUser = Integer.parseInt(jTextField2.getText());
        String idMobil = jTextField3.getText().trim();
        String tanggalSewa = jTextField4.getText().trim();
        String tanggalKembali = jTextField5.getText().trim();

        // Validasi input
        if (idMobil.isEmpty() || tanggalSewa.isEmpty() || tanggalKembali.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi");
            return;
        }

        try {
            Connection conn = databaseConnection.connect();

            // 1. Ambil harga sewa mobil dari database
            String getHargaQuery = "SELECT harga_sewa FROM mobil WHERE id_mobil = ?";
            PreparedStatement hargaStmt = conn.prepareStatement(getHargaQuery);
            hargaStmt.setString(1, idMobil);
            ResultSet rs = hargaStmt.executeQuery();

            if (!rs.next()) {
                JOptionPane.showMessageDialog(this, "Mobil tidak ditemukan");
                return;
            }

            double hargaPerHari = rs.getDouble("harga_sewa");

            // 2. Hitung jumlah hari dan total biaya
            java.sql.Date tglSewa = java.sql.Date.valueOf(tanggalSewa);
            java.sql.Date tglKembali = java.sql.Date.valueOf(tanggalKembali);

            long diffDays = ChronoUnit.DAYS.between(tglSewa.toLocalDate(), tglKembali.toLocalDate());
            int jumlahHari = (int) Math.max(diffDays, 1);
            double totalBiaya = hargaPerHari * jumlahHari;

            // 3. Insert data ke rental dengan total biaya yang dihitung
            String insertQuery = "INSERT INTO rental (id_user, id_mobil, tanggal_sewa, tanggal_kembali, total_biaya, status) "
            + "VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement stmt = conn.prepareStatement(insertQuery);
            stmt.setInt(1, idUser);
            stmt.setString(2, idMobil);
            stmt.setDate(3, tglSewa);
            stmt.setDate(4, tglKembali);
            stmt.setDouble(5, totalBiaya);
            stmt.setString(6, gstatus);
            stmt.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data berhasil disimpan. Total biaya: " + totalBiaya);

            // Reset form
            jTextField2.setText("");
            jTextField3.setText("");
            jTextField4.setText("");
            jTextField5.setText("");
            jComboBox1.setSelectedIndex(-1);
            tampilkanRental();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if(selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit");
            return;
        }

        // Get data from selected row
        int idRental = (int) jTable1.getValueAt(selectedRow, 0);
        int idUser = (int) jTable1.getValueAt(selectedRow, 1);
        String idMobil = (String) jTable1.getValueAt(selectedRow, 3);
        String tanggalSewa = jTable1.getValueAt(selectedRow, 6).toString().split(" ")[0];
        String tanggalKembali = jTable1.getValueAt(selectedRow, 7).toString().split(" ")[0];
        String status = jTable1.getValueAt(selectedRow, 9).toString();

        // Populate form fields with selected data
        jTextField1.setText(String.valueOf(idRental));
        jTextField2.setText(String.valueOf(idUser));
        jTextField3.setText(String.valueOf(idMobil));
        jTextField4.setText(tanggalSewa);
        jTextField5.setText(tanggalKembali);
        jComboBox1.setSelectedItem(status);
        jTextField1.setEnabled(false); // Disable ID field

        // Change save button to update mode
        jButton1.setText("Update");
        jButton1.removeActionListener(jButton1.getActionListeners()[0]);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDataRental();
            }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if(jComboBox1.getSelectedIndex() == 0){
            gstatus = "pending";
        }else if(jComboBox1.getSelectedIndex() == 1){
            gstatus = "diproses";
        }else if(jComboBox1.getSelectedIndex() == 2){
            gstatus = "selesai";
        }else if(jComboBox1.getSelectedIndex() == 3){
            gstatus = "dibatalkan";
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        new dashboardPegawai().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

     private void updateDataRental() {
    try {
        // Validasi input
        if (jTextField4.getText().trim().isEmpty() || 
            jTextField5.getText().trim().isEmpty() || 
            jComboBox1.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Semua field wajib diisi!");
            return;
        }
        
        int id_rental = Integer.parseInt(jTextField1.getText().trim());
        int id_user = Integer.parseInt(jTextField2.getText().trim());
        String id_mobil = jTextField3.getText().trim();
        String tanggalSewa = jTextField4.getText().trim();
        String tanggalKembali = jTextField5.getText().trim();
        String statusBaru = (String) jComboBox1.getSelectedItem();
        
        try (Connection conn = databaseConnection.connect()) {
            conn.setAutoCommit(false); // Mulai transaction
            
            try {
                // 1. Ambil status rental lama untuk perbandingan
                String getStatusQuery = "SELECT status, id_mobil FROM rental WHERE id_rental = ?";
                String statusLama = "";
                String idMobilLama = "";
                
                try (PreparedStatement statusStmt = conn.prepareStatement(getStatusQuery)) {
                    statusStmt.setInt(1, id_rental);
                    ResultSet statusRs = statusStmt.executeQuery();
                    if (statusRs.next()) {
                        statusLama = statusRs.getString("status");
                        idMobilLama = statusRs.getString("id_mobil");
                    }
                }
                
                // 2. Hitung ulang total biaya
                String getHargaQuery = "SELECT harga_sewa FROM mobil WHERE id_mobil = ?";
                double totalBiaya = 0;
                
                try (PreparedStatement hargaStmt = conn.prepareStatement(getHargaQuery)) {
                    hargaStmt.setString(1, id_mobil);
                    ResultSet rs = hargaStmt.executeQuery();
                    if (!rs.next()) {
                        JOptionPane.showMessageDialog(this, "Mobil tidak ditemukan");
                        return;
                    }
                    
                    LocalDate sewaDate = LocalDate.parse(tanggalSewa);
                    LocalDate kembaliDate = LocalDate.parse(tanggalKembali);
                    double hargaPerHari = rs.getDouble("harga_sewa");
                    long diffDays = ChronoUnit.DAYS.between(sewaDate, kembaliDate);
                    totalBiaya = hargaPerHari * Math.max(diffDays, 1);
                }
                
                // 3. Update data rental
                String updateRentalQuery = "UPDATE rental SET id_user=?, id_mobil=?, tanggal_sewa=?, " +
                           "tanggal_kembali=?, total_biaya=?, status=? WHERE id_rental=?";
                
                try (PreparedStatement updateStmt = conn.prepareStatement(updateRentalQuery)) {
                    updateStmt.setInt(1, id_user);
                    updateStmt.setString(2, id_mobil);
                    updateStmt.setDate(3, java.sql.Date.valueOf(LocalDate.parse(tanggalSewa)));
                    updateStmt.setDate(4, java.sql.Date.valueOf(LocalDate.parse(tanggalKembali)));
                    updateStmt.setDouble(5, totalBiaya);
                    updateStmt.setString(6, statusBaru);
                    updateStmt.setInt(7, id_rental);
                    
                    int rowsUpdated = updateStmt.executeUpdate();
                    if (rowsUpdated == 0) {
                        throw new SQLException("Gagal mengupdate data rental");
                    }
                }
                
                // 4. Handle perubahan status mobil
                handleStatusMobilChange(conn, statusLama, statusBaru, idMobilLama, id_mobil);
                
                conn.commit(); // Commit transaction
                
                JOptionPane.showMessageDialog(this, "Data Rental berhasil diupdate.");
                
                // Reset form
                resetFormRental();
                tampilkanRental();
                
            } catch (SQLException e) {
                conn.rollback(); // Rollback jika ada error
                JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage());
                e.printStackTrace();
                throw e;
            }
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Format angka tidak valid");
    } catch (DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "Format tanggal salah (gunakan yyyy-mm-dd)");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        e.printStackTrace();
    }
}

// Method untuk handle perubahan status mobil berdasarkan perubahan status rental
private void handleStatusMobilChange(Connection conn, String statusLama, String statusBaru, 
                                   String idMobilLama, String idMobilBaru) throws SQLException {
    
    // Jika mobil berubah, update status mobil lama dan baru
    if (!idMobilLama.equals(idMobilBaru)) {
        // Mobil lama kembali tersedia (kecuali jika masih ada rental aktif)
        updateStatusMobilBerdasarkanRental(conn, idMobilLama);
        
        // Mobil baru menjadi disewa (jika status rental bukan selesai)
        if (!"selesai".equals(statusBaru)) {
            updateStatusMobil(conn, idMobilBaru, "disewa");
        }
    }
    
    // Handle perubahan status rental
    if (!statusLama.equals(statusBaru)) {
        if ("selesai".equals(statusBaru)) {
            // Jika rental selesai, cek apakah mobil bisa dikembalikan ke status tersedia
            updateStatusMobilBerdasarkanRental(conn, idMobilBaru);
        } else if ("selesai".equals(statusLama) && !"selesai".equals(statusBaru)) {
            // Jika rental yang tadinya selesai diubah jadi status lain, mobil jadi disewa lagi
            updateStatusMobil(conn, idMobilBaru, "disewa");
        }
    }
}

// Method untuk update status mobil berdasarkan rental yang masih aktif
private void updateStatusMobilBerdasarkanRental(Connection conn, String idMobil) throws SQLException {
    // Cek apakah masih ada rental aktif untuk mobil ini
    String checkActiveRentalQuery = "SELECT COUNT(*) as count FROM rental WHERE id_mobil = ? AND status != 'selesai'";
    
    try (PreparedStatement checkStmt = conn.prepareStatement(checkActiveRentalQuery)) {
        checkStmt.setString(1, idMobil);
        ResultSet rs = checkStmt.executeQuery();
        
        if (rs.next()) {
            int activeRentals = rs.getInt("count");
            String statusMobil = (activeRentals > 0) ? "disewa" : "tersedia";
            updateStatusMobil(conn, idMobil, statusMobil);
        }
    }
}

// Method untuk update status mobil
private void updateStatusMobil(Connection conn, String idMobil, String status) throws SQLException {
    String sql = "UPDATE mobil SET status = ? WHERE id_mobil = ?";
    try (PreparedStatement stmt = conn.prepareStatement(sql)) {
        stmt.setString(1, status);
        stmt.setString(2, idMobil);
        int rowsAffected = stmt.executeUpdate();
        
        if (rowsAffected > 0) {
            System.out.println("Status mobil " + idMobil + " berhasil diupdate menjadi: " + status);
        } else {
            throw new SQLException("Gagal update status mobil untuk ID: " + idMobil);
        }
    }
}

// Method untuk reset form
private void resetFormRental() {
    jTextField1.setText("");
    jTextField2.setText("");
    jTextField3.setText("");
    jTextField4.setText("");
    jTextField5.setText("");
    jComboBox1.setSelectedIndex(-1);
    jTextField1.setEnabled(true);
    
    // Change button back to save mode
    jButton1.setText("Simpan");
    jButton1.removeActionListener(jButton1.getActionListeners()[0]);
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rental.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rental().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
